### ISSUE TITLE
Add Django news system

### ISSUE THREAD

**Issue by ixio** [Project-OSmOSE/osmose-app#107]
Make it so the team can easily add and edit news items from Django interface.

We should probably use https://github.com/tinymce/tinymce et https://github.com/jazzband/django-tinymce.

There should be 2 endpoints :

* `/api/news/{id}` : return the data about a specific news. The data is in json format. The news object contains the following properties : 
    * id : the id of the article
    * title : the title of the news in plain text
    * body : the body of the article in HTML
    * date : date of publication
    * vignette : link to a small image in 4:3 ratio to illustrate the news
    * intro : short text to introduce the article in HTML. (max length to be determined)

* `/api/news` : returns a list of every news in json format. Each news object contains the attributes listed above. List must be in reverse chronological order (most recent on top).

**Comment by flo-bou** [comment]
Pour garder une balise h1 unique par page, il pourrait être intéressant d'empêcher l'utilisation des titres h1 dans le corps de l'éditeur tinyMCE. À voir si cela est facile à mettre en place.

**Comment by flo-bou** [comment]
Do not forget to update the poetry.lock file after the tinyMCE addition.
