### ISSUE TITLE
New People page

### ISSUE THREAD

**Issue by flo-bou** [Project-OSmOSE/osmose-app#118]
Après la réunion du 5 octobre, il a été demandé de réaliser une nouvelle version de la page « People ».

- [x] virer « Who are we », photo et text et logo
- [x] faire mosaïque de visages comme sur https://www.liabebest.org/laboratoire/equipe-team 
- [x] une mini page web par personne 
- [x] ajouter par personne sur mosaique les affiliations + statut comme dans https://www.observatoire-pelagis.cnrs.fr/pelagis-2/lequipe/ 
- [x] titre PEOPLE -> Our team

**Comment by ElodieENSTA** [comment]
Maquette validé par l'équipe :
https://www.figma.com/file/7DhJNa7BoixjV1sMag72MS/OSmOSE-vitrine?type=design&node-id=0%3A1&mode=design&t=Mr3SCE2O9n1DC8xS-1
