### ISSUE TITLE
Change display of News Page

### ISSUE THREAD

**Issue by flo-bou** [Project-OSmOSE/osmose-app#119]
Après la réunion du 5 octobre, il a été demandé de changer l'affichage de la page "news" en s'inspirant d'un affichage en cards comme sur in https://www.observatoire-pelagis.cnrs.fr/echouages/seminaires-rne/

On souhaite un affichage similaire pour la page  «Projects»

**Comment by ElodieENSTA** [comment]
Maquette validé par l'équipe :
https://www.figma.com/file/7DhJNa7BoixjV1sMag72MS/OSmOSE-vitrine?type=design&node-id=0%3A1&mode=design&t=Mr3SCE2O9n1DC8xS-1
