### ISSUE TITLE
Add confidence indicator to annotation

### ISSUE THREAD

**Issue by ixio** [Project-OSmOSE/osmose-app#22]
indice de confiance, paramétrable, facultatif :avoir seulement 2 niveaux : ‘confiant’ (coché par défaut) et ‘pas confiant’. Quand l’annotateur coche ‘pas confiant’

**Comment by Qouagga** [comment]
Il peut être défini au niveau de la campagne.
Par défaut : 1 confiant, 0 pas confiant.
Niveau de confiance : nombre et texte optionnel

**Comment by ixio** [comment]
Reprécisons : 1-0, ou un nombre à choisir en début de campagne pour le nombre de niveau de confiances ou pas d'indicateur de confiance. Par défaut c'est le choix max qui est choisis lors des annotations.

**Comment by ElodieENSTA** [comment]
Plusieurs problèmes observés :
- A la création de la campagne d'annotation je ne peux pas sélectionner "No confidence indicator set", ça reste sur "Select a confidence indicator set" (et je peux valider la config)
- En accédant à une tache de la campagne j'ai l'erreur `Error while loading task: TypeError: Cannot read properties of null (reading 'confidenceIndicators')`
- Il set obligatoire de sélectionner un "indicator set"
