### ISSUE TITLE
Update people page

### ISSUE THREAD

**Issue by Qouagga** [Project-OSmOSE/osmose-app#92]
Page people :
- [x] add Gabriel
- [x] add Pierre-Yves
- [x] add Quentin
- [x] add Mathilde
- [x] remove sections AIE & ODE
- [x] use chronological order
- [x] update ENSTA logo
- [x] remove IMT logo
- [x] add Lab-STICC logo
- [x] add IUEM logo
- [x] fix image ratio
- [x] compress images
- [x] re-add Paul
- [x] ask for developers' bio and portrait (Florent added)
- [x] change team image
- [x] add Quotation mark for mini-bio
- [x] add jobs/role for team members

Page publication :
- [x] compress banner image
- [x] updates list according to document in GDrive
- [ ] ~~add pdf links~~
- [x]  https://dyni.pages.lis-lab.fr/publications/, en gras les membres osmose

Home Page :
- [x] Funders -> Collaborators & Funders
- [x] logo : ENSTA B / Lab STICC / UBO / IUEM / Sorbonne Univ / CEBC / OFB

**Branch : feature/update-people-page**

**Comment by flo-bou** [comment]
Nettoyer l'historique d'anciens commits non désirés.
