### ISSUE TITLE
Fix tag panels in annotator

### ISSUE THREAD

**Issue by ixio** [Project-OSmOSE/osmose-app#96]
In the annotator we added a presence / absence panel and now the different tags & other panels have weird/bad shapes, there is text overflowing. This should be cleaned.

**Comment by MaelleTtrt** [comment]
![Annotation 2023-08-29 145008](https://github.com/Project-OSmOSE/osmose-app/assets/48910568/f9d49caf-cf10-455c-923d-ad0bd1519a11)
